language: node_js

node_js:
  - 8
  - 10
  - 12

sudo: false

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.6.0
  - export PATH=$HOME/.yarn/bin:$PATH

cache:
  yarn: true

scripts:
  - yarn build
  - yarn test